theme: jekyll-theme-cayman
title: A list of Bad Token Launches - editable by the community
description: Please feel free to add to [list](https://github.com/badtokenlaunch/badtokenlaunch.github.io) as needed 
